# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18773f240fe98c9669912b3a7a05fd50decdaed573f69417c1bd538886b55c5f817829c28454f7ff74f2424281eca4852a3406efdf6bc200291616bac955c453

test:
  secret_key_base: 09244bb5bc5f6851ed4fd57d6a91dce36f40d0400a700c0c2e28f1c0cb9cba7c4d601857b335a6d7ef7ad5751350d5cfbe72fd98c1216b5ca199fb3b5a177f75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
